## WindSentinel RabbitMQ Configuration

# Default user and password (env var'lardan gelecek)
default_user = admin
default_pass = admin123

# Management plugin (UI dashboard)
management.load_definitions = /etc/rabbitmq/definitions.json

# Logging
log.console = true
log.console.level = info

# Daha hızlı başlangıç ve düşük bellek kullanımı
vm_memory_high_watermark.relative = 0.4
