import { useState, createContext, useContext } from 'react';

const translations = {
  tr: {
    // Nav
    dashboard: 'Kontrol Paneli',
    turbines: 'Türbinler',
    alarms: 'Alarmlar',
    systemStatus: 'Sistem Durumu',
    monitoring: 'İzleme',
    system: 'Sistem',
    logout: 'Çıkış Yap',
    live: 'CANLI',
    searchTurbine: 'Türbin ara...',
    subtitle: 'Erken Arıza Tespit Sistemi',

    // Dashboard
    controlPanel: 'Kontrol Paneli',
    realTimeMonitoring: 'Gerçek zamanlı izleme',
    last24h: 'Son 24 Saat',
    activeTurbine: 'Aktif Türbin',
    allOperational: 'Tümü operasyonel',
    offline: 'devre dışı',
    resolutionRate: 'Çözüm Oranı',
    resolved: 'çözüldü',
    avgRiskScore: 'Ort. Risk Skoru',
    points100: '/100 puan',
    activeAlarm: 'Aktif Alarm',
    turbinesAffected: 'türbin etkilendi',
    turbineRiskStatus: 'Türbin Risk Durumu',
    activeAlarms: 'Aktif Alarmlar',
    all: 'Tümü',
    riskScoreTrend: 'Risk Skoru Trendi',
    manualMeasurement: 'Manuel Ölçüm',
    enterSensorValues: 'Sensör değerlerini girin',
    calculateRisk: 'Risk Hesapla',
    calculating: 'Hesaplanıyor...',
    riskScore: 'Risk Skoru',
    powerDeviation: 'Güç Sapması',
    tempRisk: 'Sıcaklık Riski',
    vibRisk: 'Titreşim Riski',
    noActiveAlarm: 'Aktif alarm yok',
    systemHealthy: 'Sistem sağlıklı çalışıyor',
    farm: 'Çiftlik',
    status: 'Durum',
    alarm: 'Alarm',
    active: 'AKTİF',
    closed: 'KAPALI',
    loading: 'Yükleniyor...',

    // Alarms
    alarmManagement: 'Alarm Yönetimi',
    anomalyResults: 'Anomali tespit sonuçları ve alarm geçmişi',
    allFilter: 'Tümü',
    activeFilter: 'Aktif',
    resolvedFilter: 'İncelendi',
    records: 'kayıt',
    id: 'ID',
    turbine: 'Türbin',
    type: 'Tür',
    score: 'Skor',
    confidence: 'Güven',
    date: 'Tarih',
    action: 'İşlem',
    resolve: 'Çöz',
    resolvedStatus: 'İncelendi',
    activeStatus: 'Aktif',
    notFound: 'Alarm bulunamadı',

    // Turbines
    turbineStatuses: 'Türbin Durumları',
    realTimeData: 'Gerçek zamanlı izleme verileri',
    activeAlarmLabel: 'Aktif Alarm',
    farmLabel: 'Çiftlik',
    back: 'Geri',
    alarmHistory: 'Alarm Geçmişi',
    activeAlarmsLabel: 'Aktif Alarmlar',
    resolvedLabel: 'İncelendi',
    totalEvents: 'Toplam Olay',
    noAlarmRecorded: 'Bu türbin için alarm kaydedilmemiş',
    critical: 'KRİTİK',
    warning: 'UYARI',
    info: 'BİLGİ',
    normal: 'NORMAL',

    // Severity
    severityCritical: 'Kritik',
    severityWarning: 'Uyarı',
    severityActive: 'Aktif',

    // Manual measurement
    windSpeed: 'Rüzgâr Hızı',
    powerOutput: 'Güç Üretimi',
    generatorRpm: 'Jeneratör RPM',
    gearboxTemp: 'Dişli Kutusu Sıcaklığı',
    vibrationLevel: 'Titreşim Seviyesi',

    // Login
    loginTitle: 'Giriş Yap',
    loginSubtitle: 'Türbin izleme paneline erişim için giriş yapın.',
    email: 'E-posta',
    password: 'Şifre',
    loggingIn: 'Giriş yapılıyor...',
    login: 'Giriş Yap',

    // Time
    justNow: 'Az önce',
    minutesAgo: 'dk önce',
    hoursAgo: 'saat önce',
    daysAgo: 'gün önce',

    // Landing
    landingSubtitle: 'ERKEN ARIZA TESPİT SİSTEMİ',
    navFeatures: 'Çözümlerimiz',
    navAudience: 'Hedef Kitlemiz',
    navHow: 'Nasıl Çalışır',
    navAbout: 'Hakkımızda',
    signIn: 'Giriş Yap',
    getDemo: 'Demo Al',
    heroBadge: 'Yapay Zeka Destekli Erken Uyarı',
    goToPanel: 'Panele Git',
    howItWorks: 'Nasıl Çalışır?',
    slide1Title: 'Rüzgar türbinleriniz için',
    slide1Highlight: 'akıllı arıza tespiti',
    slide1Desc: 'SCADA verileri ve saha ölçümleri üzerinde çalışan yapay zeka modelleri, potansiyel arızaları saatler öncesinden tespit eder.',
    slide2Title: 'Bakım maliyetlerinizi',
    slide2Highlight: 'gözle görülür şekilde azaltın',
    slide2Desc: 'Reaktif bakımdan proaktif bakıma geçiş yaparak beklenmedik duruşları minimize edin, üretim kaybını önleyin.',
    slide3Title: 'Gerçek zamanlı izleme,',
    slide3Highlight: 'anlık bildirimler',
    slide3Desc: 'Web paneli ve mobil uygulama üzerinden türbin durumunu 7/24 takip edin, kritik uyarıları anında alın.',
    statTurbines: 'Aktif Türbin',
    statInference: 'Inference Süresi',
    statLeadTime: 'Erken Uyarı Süresi',
    statF1: 'F1 Skoru',
    featuresTitle: 'Neden WIND Sentinel?',
    featuresSubtitle: 'Türbin izleme sürecinizi dönüştüren temel yetenekler.',
    feat1Title: 'Erken Arıza Tespiti',
    feat1Desc: 'Arızadan saatler önce uyarı üreterek planlı bakıma geçiş sağlar.',
    feat2Title: 'Gerçek Zamanlı İzleme',
    feat2Desc: 'Her ölçüm milisaniyeler içinde skorlanır. Gecikme yok, veri kaybı yok.',
    feat3Title: 'Saha Entegrasyonu',
    feat3Desc: 'Mobil uygulama ile girilen manuel ölçümler SCADA verisiyle birleştirilir.',
    feat4Title: 'Güvenilir Sonuçlar',
    feat4Desc: 'Düşük yanlış alarm oranı ile bakım ekibi alarm yorgunluğu yaşamaz.',
    audienceTitle: 'Kimlere Hitap Ediyoruz?',
    audienceSubtitle: 'Rüzgar enerjisi ekosistemindeki tüm paydaşlar için tasarlandı.',
    aud1Title: 'Saha Mühendisleri',
    aud1Desc: 'Türbin başında çalışan teknisyenler, mobil uygulama üzerinden anlık uyarı alır ve manuel ölçüm girebilir.',
    aud2Title: 'Kontrol Merkezi Operatörleri',
    aud2Desc: 'Web paneli üzerinden tüm türbin filosunu gerçek zamanlı izler, alarm yönetimi yapar.',
    aud3Title: 'Bakım Planlama Ekipleri',
    aud3Desc: 'Erken uyarılar sayesinde bakım takvimini optimize eder, beklenmedik duruşları minimize eder.',
    aud4Title: 'Enerji Şirketi Yöneticileri',
    aud4Desc: 'Operasyonel verimliliği artırır, bakım maliyetlerini düşürür, türbin ömrünü uzatır.',
    howTitle: 'Üç Adımda Erken Uyarı',
    howSubtitle: 'Sensör verisinden uyarıya kadar tüm süreç otomatik işler.',
    step1Title: 'Veri Toplama',
    step1Desc: 'SCADA sensörlerinden gelen zaman serisi verileri ve teknisyenlerin mobil uygulama üzerinden girdiği manuel ölçümler sisteme akar.',
    step1Tag: 'Otomatik + Manuel',
    step2Title: 'Yapay Zeka Analizi',
    step2Desc: 'Makine öğrenmesi modelleri sensör verilerini analiz eder, normal davranıştan sapmaları tespit eder ve risk skoru üretir.',
    step2Tag: 'Anomali Tespiti',
    step3Title: 'Erken Uyarı',
    step3Desc: 'Risk skoru eşiği aştığında bakım ekibi web paneli ve mobil bildirim ile anında haberdar edilir.',
    step3Tag: 'Anlık Bildirim',
    aboutTitle: 'WIND Sentinel Nedir?',
    missionTitle: 'Misyonumuz',
    missionText: 'Rüzgar enerjisi operatörlerine beklenmedik türbin arızalarından önce uyarı veren, yapay zeka destekli bir erken uyarı platformudur. Reaktif bakımdan proaktif bakıma geçişi kolaylaştırmak ve operasyonel maliyetleri azaltmak temel hedefimizdir.',
    visionTitle: 'Vizyonumuz',
    visionText: 'Rüzgar enerjisi sektöründe yapay zeka destekli bakım yönetiminin standart haline gelmesini hedefliyoruz. Türbin filosu büyüklüğünden bağımsız, her ölçekteki operatöre erişilebilir ve ölçeklenebilir çözümler sunmak vizyonumuzdur.',
    ctaTitle: 'Türbinlerinizi korumaya başlayın',
    ctaSubtitle: 'Demo hesabı ile sistemi hemen deneyin.',
    footerText: 'Rüzgar türbini erken arıza tespit sistemi',
    backToHome: '← Ana sayfaya dön',
  },
  en: {
    dashboard: 'Dashboard',
    turbines: 'Turbines',
    alarms: 'Alarms',
    systemStatus: 'System Status',
    monitoring: 'Monitoring',
    system: 'System',
    logout: 'Logout',
    live: 'LIVE',
    searchTurbine: 'Search turbine...',
    subtitle: 'Early Fault Detection System',

    controlPanel: 'Dashboard',
    realTimeMonitoring: 'Real-time monitoring',
    last24h: 'Last 24 Hours',
    activeTurbine: 'Active Turbines',
    allOperational: 'All operational',
    offline: 'offline',
    resolutionRate: 'Resolution Rate',
    resolved: 'resolved',
    avgRiskScore: 'Avg. Risk Score',
    points100: '/100 points',
    activeAlarm: 'Active Alarms',
    turbinesAffected: 'turbines affected',
    turbineRiskStatus: 'Turbine Risk Status',
    activeAlarms: 'Active Alarms',
    all: 'All',
    riskScoreTrend: 'Risk Score Trend',
    manualMeasurement: 'Manual Measurement',
    enterSensorValues: 'Enter sensor values',
    calculateRisk: 'Calculate Risk',
    calculating: 'Calculating...',
    riskScore: 'Risk Score',
    powerDeviation: 'Power Deviation',
    tempRisk: 'Temperature Risk',
    vibRisk: 'Vibration Risk',
    noActiveAlarm: 'No active alarms',
    systemHealthy: 'System running healthy',
    farm: 'Farm',
    status: 'Status',
    alarm: 'Alarm',
    active: 'ACTIVE',
    closed: 'OFFLINE',
    loading: 'Loading...',

    alarmManagement: 'Alarm Management',
    anomalyResults: 'Anomaly detection results and alarm history',
    allFilter: 'All',
    activeFilter: 'Active',
    resolvedFilter: 'Resolved',
    records: 'records',
    id: 'ID',
    turbine: 'Turbine',
    type: 'Type',
    score: 'Score',
    confidence: 'Confidence',
    date: 'Date',
    action: 'Action',
    resolve: 'Resolve',
    resolvedStatus: 'Resolved',
    activeStatus: 'Active',
    notFound: 'No alarms found',

    turbineStatuses: 'Turbine Status',
    realTimeData: 'Real-time monitoring data',
    activeAlarmLabel: 'Active Alarms',
    farmLabel: 'Farm',
    back: 'Back',
    alarmHistory: 'Alarm History',
    activeAlarmsLabel: 'Active Alarms',
    resolvedLabel: 'Resolved',
    totalEvents: 'Total Events',
    noAlarmRecorded: 'No alarms recorded for this turbine',
    critical: 'CRITICAL',
    warning: 'WARNING',
    info: 'INFO',
    normal: 'NORMAL',

    severityCritical: 'Critical',
    severityWarning: 'Warning',
    severityActive: 'Active',

    windSpeed: 'Wind Speed',
    powerOutput: 'Power Output',
    generatorRpm: 'Generator RPM',
    gearboxTemp: 'Gearbox Temperature',
    vibrationLevel: 'Vibration Level',

    loginTitle: 'Sign In',
    loginSubtitle: 'Sign in to access the turbine monitoring panel.',
    email: 'Email',
    password: 'Password',
    loggingIn: 'Signing in...',
    login: 'Sign In',

    justNow: 'Just now',
    minutesAgo: 'min ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',

    // Landing
    landingSubtitle: 'EARLY FAULT DETECTION SYSTEM',
    navFeatures: 'Our Solutions',
    navAudience: 'Target Audience',
    navHow: 'How It Works',
    navAbout: 'About Us',
    signIn: 'Sign In',
    getDemo: 'Get Demo',
    heroBadge: 'AI-Powered Early Warning',
    goToPanel: 'Go to Panel',
    howItWorks: 'How It Works?',
    slide1Title: 'For your wind turbines,',
    slide1Highlight: 'intelligent fault detection',
    slide1Desc: 'AI models running on SCADA data and field measurements detect potential faults hours in advance.',
    slide2Title: 'Reduce your maintenance costs',
    slide2Highlight: 'significantly',
    slide2Desc: 'Transition from reactive to proactive maintenance, minimize unexpected downtime, prevent production loss.',
    slide3Title: 'Real-time monitoring,',
    slide3Highlight: 'instant notifications',
    slide3Desc: 'Monitor turbine status 24/7 via web panel and mobile app, receive critical alerts instantly.',
    statTurbines: 'Active Turbines',
    statInference: 'Inference Time',
    statLeadTime: 'Early Warning Time',
    statF1: 'F1 Score',
    featuresTitle: 'Why WIND Sentinel?',
    featuresSubtitle: 'Core capabilities that transform your turbine monitoring process.',
    feat1Title: 'Early Fault Detection',
    feat1Desc: 'Generates warnings hours before failure, enabling planned maintenance.',
    feat2Title: 'Real-Time Monitoring',
    feat2Desc: 'Every measurement is scored within milliseconds. No delay, no data loss.',
    feat3Title: 'Field Integration',
    feat3Desc: 'Manual measurements entered via mobile app are combined with SCADA data.',
    feat4Title: 'Reliable Results',
    feat4Desc: 'Low false alarm rate ensures maintenance teams don\'t experience alert fatigue.',
    audienceTitle: 'Who Is It For?',
    audienceSubtitle: 'Designed for all stakeholders in the wind energy ecosystem.',
    aud1Title: 'Field Engineers',
    aud1Desc: 'Technicians working at turbine sites receive instant alerts and can enter manual measurements via mobile app.',
    aud2Title: 'Control Center Operators',
    aud2Desc: 'Monitor the entire turbine fleet in real-time via web panel, manage alarms.',
    aud3Title: 'Maintenance Planning Teams',
    aud3Desc: 'Optimize maintenance schedules with early warnings, minimize unexpected downtime.',
    aud4Title: 'Energy Company Executives',
    aud4Desc: 'Increase operational efficiency, reduce maintenance costs, extend turbine lifespan.',
    howTitle: 'Early Warning in Three Steps',
    howSubtitle: 'The entire process from sensor data to alert runs automatically.',
    step1Title: 'Data Collection',
    step1Desc: 'Time series data from SCADA sensors and manual measurements entered by technicians via mobile app flow into the system.',
    step1Tag: 'Automatic + Manual',
    step2Title: 'AI Analysis',
    step2Desc: 'Machine learning models analyze sensor data, detect deviations from normal behavior, and generate risk scores.',
    step2Tag: 'Anomaly Detection',
    step3Title: 'Early Warning',
    step3Desc: 'When the risk score exceeds the threshold, the maintenance team is instantly notified via web panel and mobile notification.',
    step3Tag: 'Instant Notification',
    aboutTitle: 'What is WIND Sentinel?',
    missionTitle: 'Our Mission',
    missionText: 'An AI-powered early warning platform that alerts wind energy operators before unexpected turbine failures. Our core goal is to facilitate the transition from reactive to proactive maintenance and reduce operational costs.',
    visionTitle: 'Our Vision',
    visionText: 'We aim to make AI-powered maintenance management the standard in the wind energy sector. Our vision is to provide accessible and scalable solutions to operators of all sizes, regardless of fleet size.',
    ctaTitle: 'Start protecting your turbines',
    ctaSubtitle: 'Try the system now with a demo account.',
    footerText: 'Wind turbine early fault detection system',
    backToHome: '← Back to home',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('windsentinel_lang') || 'tr');

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('windsentinel_lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.tr[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
